<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
     <xacro:property name="lidar_length" value="0.1" />
     <xacro:property name="lidar_width" value="0.1" />
     <xacro:property name="lidar_height" value="0.03" />
     <xacro:property name="camera_length" value="0.01" />
     <xacro:property name="camera_width" value="0.1" />
     <xacro:property name="camera_height" value="0.05" />
     <link name="camera_link">
         <visual>
              <geometry>
                  <box size="${camera_length} ${camera_width} ${camera_height}" />
              </geometry>
              <material name="grey" />
         </visual>
         <collision>
              <geometry>
                  <box size="${camera_length} ${camera_width} ${camera_height}" />
              </geometry>
         </collision>  
         <xacro:box_inertia  m="0.1" l="${camera_length}" w="${camera_width}" h="${camera_height}"
                             xyz="0 0 0" rpy="0 0 0" />
     </link>

     <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="${lidar_width / 2.0}" length="${lidar_height}" />
            </geometry>
            <material name="grey" />
        </visual>    
        <collision>
            <geometry>
                <cylinder radius="${lidar_width / 2.0}" length="${lidar_height}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1" />
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" />
        </inertial>
     </link>  

     <joint name="base_camera_joint" type="fixed">
          <parent link="base_link" />
          <child link="camera_link" />
          <origin xyz="${(base_length + camera_length) / 2.0 } ${base_width / 3.5} ${base_height / 2.0}" rpy="0 0 0" />
     </joint> 

     <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar_link" />
        <origin xyz="${(base_length + lidar_length) / 2.7} ${base_width-0.53} ${base_height + lidar_height / 2.0}" rpy="0 0 0" />
     </joint> 

     <gazebo reference="camera_link">
         <material>Gazebo/Red</material>
       <sensor name="camera_sensor" type="camera">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>60.0</update_rate>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                 <frame_name>camera_link</frame_name>
            </plugin>
        </sensor>
     </gazebo>
     <gazebo reference="lidar_link">
        <material>Gazebo/Blue</material>
        <sensor name="lidar_sensor" type="ray">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>60.0</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>1</resolution>
                        <min_angle>-1.5708</min_angle>
                        <max_angle>1.5708</max_angle>
                    </horizontal>
                    <vertical>
                        <samples>1</samples>
                        <resolution>1</resolution>
                        <min_angle>0</min_angle>
                        <max_angle>0</max_angle>
                    </vertical>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>10.0</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
            <plugin name="lidar_plugin" filename="libgazebo_ros_laser.so">
                <frame_name>lidar_link</frame_name>
                <topic_name>/scan</topic_name>
            </plugin>
        </sensor>
     </gazebo>
</robot>